---
title: "Covid-19 in India"
author: "Anirudh Jayaraman"
date: "6/14/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## The Preliminaries

```{r}
library(tidyverse)
library(lubridate)
library(visreg)
library(gridExtra)
```

```{r}
# Relevant directories --------------------------------------------------------
project_dir <- "C:/git/Covid-19/"
output_dir <- paste0(project_dir, "output/")
download_dir <- paste0(project_dir, "downloaded_data/")

# Specify config --------------------------------------------------------------
conf <- config::get(file = paste0(project_dir, "conf/config.yml") )
```

Sourcing the data...
```{r}
source(paste0(project_dir, "code/source_data.R"))
```

Some stitching is required because the data are in chunks
```{r}
# Store all raw_data1, raw_data2, ... variables (dataframes) in a list 
raw_datasets <- mget(ls()[grep("raw_data[0-9]", ls(), fixed = FALSE)])

# Convert the patient level datasets from data.table to data.frame
raw_datasets <- raw_datasets %>%
  lapply(as.data.frame)

raw_datasets %>% map(.f = glimpse)
```

Ensure information in the datasets is complete
```{r}
# Ensure data corresponds to non-empty time stamps
case_time_series <- case_time_series %>% 
  filter(!is.na(Date) & Date != "")

state_wise_daily <- state_wise_daily %>% 
  filter(!is.na(Date) & Date != "")
```

Dates in case_time_series data are not in a usable Date format
```{r}
case_time_series %>% 
  pull(Date)
```

let's correct that...
```{r}
# Convert date in "dd Month" character format to Date objects with lubridate
case_ts_dates <- case_time_series %>%
  pull(Date)

# substrings corresponding to date and month
date_chars <- case_ts_dates %>% substr(start = 1, stop = 2)
month_chars <- case_ts_dates %>% substr(start = 4, stop = 6)

# transform Date variable into an easily readable format
case_time_series <- case_time_series %>%
  mutate(Date = lubridate::dmy(paste0(date_chars, "-", month_chars, "-2020")))
```

Dates in state_wise_daily are strings
```{r}
state_wise_daily %>%
  pull(Date) %>% class

state_wise_daily %>%
  pull(Date)
```

```{r}
state_wise_daily <- state_wise_daily %>%
  mutate(Date = lubridate::dmy(Date))
```

```{r}
state_wise_daily$Date %>% class
```

Get clean state-wise data
```{r}
# =============================================================================
# GET CLEAN STATE-WISE DATA
# =============================================================================

# Names of all states / UTs in the 'state_wise_daily' dataset
states <- names(state_wise_daily)[3:ncol(state_wise_daily)]

# Creates separate state level data, harvesting the 'state_wise_daily' dataset

# The state_wise_daily data has Confirmed, Recovered and Deceased data
# and hence has (3 x number_of_Dates) rows
# Confirmed corresponds to rows 1, 4, 7, and so on.
# Recovered corresponds to rows 2, 5, 8, and so on.
# Deceased corresponds to rows 3, 6, 9 and so on.

confirmed_idx <- seq(1, nrow(state_wise_daily), 3)
recovered_idx <- seq(2, nrow(state_wise_daily), 3)
deceased_idx <- seq(3, nrow(state_wise_daily), 3)

for(i in 1:length(states)){
  state_code <- states[i]
  state_wise_daily <- as.data.frame(state_wise_daily)
  
  col_idx <- which(names(state_wise_daily) == state_code)
  
  df <- data.frame(Date = unique(state_wise_daily$Date),
                   Confirmed = state_wise_daily[confirmed_idx, col_idx],
                   Recovered = state_wise_daily[recovered_idx, col_idx],
                   Deceased = state_wise_daily[deceased_idx, col_idx])
  
  
  df$Active <- cumsum(df$Confirmed) - cumsum(df$Recovered) - cumsum(df$Deceased)
  
  
  df$`Total Confirmed` <- cumsum(df$Confirmed)
  df$`Total Recovered` <- cumsum(df$Recovered)
  df$`Total Deceased` <- cumsum(df$Deceased)
  
  assign(as.character(state_code), df)
}

# Store curated state data in a list
states_data <- mget(states)  # list of states 

# States such as 'MH' and 'DL' can now be accessed directly
states_data %>% names
```
```{r}
states_data$MH %>% glimpse
```

Visualize state-wise data
```{r}
# =============================================================================
# Plotting trends state-wise
# =============================================================================

source(paste0(project_dir, "code/plot_state_trends.R"))

# Total Confirmed ---------------------------------------------------------

for(i in 1:length(states)){
  # get COVID-19 dataset for i-th state
  dat <- get(states[i])
  
  # Sve the plot
  assign(paste0("p",i), 
         dat %>%
           ggplot(mapping = aes(x = Date)) +
           geom_line(mapping = aes(y = `Total Confirmed`), 
                     color = 'steelblue', size = 1, show.legend = TRUE) +
           xlab("") + ylab("") +
           ggtitle(paste0(states[i], " Total Confirmed")))
}

plot_state_trends()

```

